<b><font color= #000066  face="Comic Sans MS,arial">
  <h1 ><i>Multiplicación de matrices</i></h1>
  <h5 ><i>Rodríguez César Axel </i></h5>
  <h5><i>Rojas Bautista Alan Daniel .</i></h5>
  </font>

#### Creación de matriz
Primeramente añadimos una función que nos permita crear una matriz $X$ de tamaño $n$x$n$, en particular con $n=2$.

In [ ]:
import numpy as np

#Se crea una función para generar una matriz de tam x tam(2x2 en este caso) con numeros aleatorios en un rango de 1 a 100 y la imprime
def creaMatriz(tam):
    #Usando la función "randint()" se crea una matriz de tam x tam con cada uno de sus elementos en un rango de 1 a 100
    a=np.random.randint(1,100,(tam,tam))
    #Se devuelve la matriz
    return a

# Se imprime la matriz
print(creaMatriz(2))

[[66 50]
 [69 90]]


Por otro lado si deseamos usar la estructura de datos **list**, podemos crear la matriz de esta forma:

In [ ]:
m1= [[3, -1, 4],[-5, 0, 2],[1, -2, 6]]
m2= [[3, 1, 5],[5, 10, 2],[2, -3, -6]]

###Multiplicaión de matrices

In [ ]:
#Multiplicacion de matrices
#se debe devolver m1*m2 con
#m1 y m2 matrices de dimensiones adecuadas
def multMatriz(m1,m2):
    resultado = np.zeros((len(m1), len(m2[0])))
    for i in range(len(m1)):
      for j in range(len(m2[0])):
        for k in range(len(m1)):
          resultado[i][j] += m1[i][k]*m2[k][j]
    return resultado



Adicionalmente para comprobar que el codigo funciona correctamente, se declaran dos matrices: (m3,m4) y se ingresan a la función.


In [ ]:
m3=creaMatriz(2)
m4=creaMatriz(2)


La multiplicación de la matrices m1 y m2 es:

In [ ]:
print(m1,"*",m2)
print("=",multMatriz(m1,m2))

[[ 4 42]
 [79 46]] * [[61 20]
 [47 80]]
= [[2218. 3440.]
 [6981. 5260.]]


La multiplicacion de las matrices m3 y m4 es:

In [ ]:
print(m3,"*",m4)
print("=",multMatriz(m3,m4))

[[97 57]
 [89  3]] * [[15 19]
 [82 63]]
= [[6129. 5434.]
 [1581. 1880.]]
